### PR TITLE
updatedColor-hexagon.css

### PR DESCRIPTION
**Pull request by jujucrystal**
A new contributor here .. :)
--

### CODE REVIEW

**Comment by jujucrystal** [comment]
A new contributor here .. :)

**Comment by web-tiki** [comment]
Hi, @jujucrystal and thx for the contribution but I don't think making the hexagon text background yellow is pretty as the body background is blue.

**Comment by poi33** [comment]
Web-tiki do we have any known issues that perhaps we can add so that contributors can try to figure out?

**Comment by web-tiki** [comment]
@poi33 not that I know of.

**Comment by jujucrystal** [comment]
[hexagon.zip](https://github.com/web-tiki/responsive-grid-of-hexagons/files/1202107/hexagon.zip)

what about now! i replace the body background!

**Pull request closed without merging**
